### ISSUE TITLE
Sound Randomly Stops

### ISSUE THREAD

**Issue by aabosh** [adamcichy/SwiftySound#23] opened 2017-11-05 19:50 UTC
Hi,

I'm using SwiftySound and I've noticed that when I play a sound, it occasionally stops out of a sudden. It does not always occur, only sometimes. When it does, it seems to happen at a random duration and is unpredictable.

I'm using `Sound.play(file: "Timer.m4a")` to play and `Sound.stop(file: "Timer.m4a")` to stop the sound. I've uploaded the audio file [here.](https://dbr.ee/jb8t)

Any help would be much appreciated, thanks!

**Comment by adamcichy** [comment] 2017-12-20 14:58
I will check it out, however it entirely depends on `AVFoundation` framework and might be not related to SwiftySound itself. Uploaded the file here so it doesn't get lost.
[Timer.m4a.zip](https://github.com/adamcichy/SwiftySound/files/1575920/Timer.m4a.zip)

**Comment by JanX2** [comment] 2018-05-30 11:17
Is this still current @aabosh?

**Comment by saranpol** [comment] 2018-10-17 17:08
I have the same problem

My work around is don't use Sound.stop(file: "your_file")
but use

```
let url = Bundle.main.url(forResource: "question_bg", withExtension: "mp3")
mSoundQuestion = Sound(url: url!)
mSoundQuestion?.play()

```
and

`mSoundQuestion?.stop()`

instead.

**Comment by adamcichy** [comment] 2018-12-22 14:11
Closing this since it isn't reproducible. I ran a final long test with the attached file and it works perfectly.

**Closed by adamcichy** 2018-12-22 14:11 UTC
